version: '3.8'

services:
  timescaledb:
    # image: timescale/timescaledb-ha:pg16-latest
    image: postgres:16
    # build:
    #  context: .
    #  dockerfile: Dockerfile.db
    container_name: turtle_db
    environment:
      - POSTGRES_USER=trading
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading_risk
    ports:
      - "5432:5432"
    volumes:
      - turtle_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: turtle_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  turtle_data:
