"""add uq_historical_atm_iv_unique

Revision ID: 017_uq_atm_iv
Revises: bf05657c4fc1
Create Date: 2025-07-05 11:46:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '017_uq_atm_iv'
down_revision = 'bf05657c4fc1'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_historical_atm_iv_unique', 'historical_atm_iv', ['trade_date', 'symbol'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_historical_atm_iv_unique', 'historical_atm_iv', type_='unique')
    # ### end Alembic commands ###
