"""Add needs_review and audit_flag to DividendDatabank

Revision ID: add_needs_review_audit_flag
Revises: fix_pe_ratio_length_006
Create Date: 2026-08-23 10:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_needs_review_audit_flag'
down_revision = '20260714072610'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividend_databank', sa.Column('needs_review', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('dividend_databank', sa.Column('audit_flag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dividend_databank', 'audit_flag')
    op.drop_column('dividend_databank', 'needs_review')
    # ### end Alembic commands ###
