"""add parsed dividend amount and type

Revision ID: 014_parsed_dividend
Revises: 013_add_unique_constraint_to_fii_dii
Create Date: 2026-03-20 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014_parsed_dividend'
down_revision = "013_fii_dii_unique"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_actions', sa.Column('parsed_dividend_amount', sa.Float(), nullable=True))
    op.add_column('corporate_actions', sa.Column('dividend_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_actions', 'dividend_type')
    op.drop_column('corporate_actions', 'parsed_dividend_amount')
    # ### end Alembic commands ###
