"""Add extracted dividend to board meetings

Revision ID: b6f693c0aeff
Revises:
Create Date: 2026-05-09 08:25:30.181340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f693c0aeff'
down_revision: Union[str, Sequence[str], None] = '016_bhavcopy_fo_duplicates_fix'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_meetings', sa.Column('extracted_dividend_amount', sa.Float(), nullable=True))
    op.add_column('board_meetings', sa.Column('extracted_dividend_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_meetings', 'extracted_dividend_type')
    op.drop_column('board_meetings', 'extracted_dividend_amount')
    # ### end Alembic commands ###
