"""create pe ratio idx table

Revision ID: create_pe_ratio_idx_008
Revises: create_corporate_actions_007
Create Date: 2026-02-28 04:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'create_pe_ratio_idx_008'
down_revision = 'create_corporate_actions_007'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_pe_ratio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=150), nullable=False),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('div_yield', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('date', 'id'),
    sa.UniqueConstraint('date', 'symbol', name='uq_index_pe_ratio_unique')
    )
    op.create_index(op.f('ix_index_pe_ratio_date'), 'index_pe_ratio', ['date'], unique=False)
    op.create_index(op.f('ix_index_pe_ratio_symbol'), 'index_pe_ratio', ['symbol'], unique=False)

    # Convert to Timescale hypertable
    conn = op.get_bind()
    conn.execute(sa.text("SELECT create_hypertable('index_pe_ratio', 'date', if_not_exists => TRUE)"))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_index_pe_ratio_symbol'), table_name='index_pe_ratio')
    op.drop_index(op.f('ix_index_pe_ratio_date'), table_name='index_pe_ratio')
    op.drop_table('index_pe_ratio')
    # ### end Alembic commands ###
