"""add_expiry_dates_to_derivatives_analysis

Revision ID: add_expiry_dates
Revises: create_pe_ratio_idx_008
Create Date: 2026-03-10 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_expiry_dates'
down_revision = 'a836a8ddcd34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_derivatives_analysis', sa.Column('near_expiry_date', sa.Date(), nullable=True))
    op.add_column('daily_derivatives_analysis', sa.Column('next_expiry_date', sa.Date(), nullable=True))
    op.add_column('daily_derivatives_analysis', sa.Column('far_expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_derivatives_analysis', 'far_expiry_date')
    op.drop_column('daily_derivatives_analysis', 'next_expiry_date')
    op.drop_column('daily_derivatives_analysis', 'near_expiry_date')
    # ### end Alembic commands ###
