"""create corporate actions table

Revision ID: create_corporate_actions_007
Revises: fix_pe_ratio_length_006
Create Date: 2026-02-28 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'create_corporate_actions_007'
down_revision = 'fix_pe_ratio_length_006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('bc_start_date', sa.Date(), nullable=True),
    sa.Column('bc_end_date', sa.Date(), nullable=True),
    sa.Column('nd_start_date', sa.Date(), nullable=True),
    sa.Column('nd_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('date', 'id'),
    sa.UniqueConstraint('date', 'symbol', 'purpose', name='uq_corp_action_unique')
    )
    op.create_index(op.f('ix_corporate_actions_date'), 'corporate_actions', ['date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_symbol'), 'corporate_actions', ['symbol'], unique=False)

    # Convert to Timescale hypertable
    conn = op.get_bind()
    conn.execute(sa.text("SELECT create_hypertable('corporate_actions', 'date', if_not_exists => TRUE)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_actions_symbol'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
