from jinja2 import Template
import pdfkit # Assumes wkhtmltopdf is installed, or we just render HTML
from datetime import date

class PDFGenerator:
    """
    Generates Analyst Commentary PDF.
    """
    def generate_report(self, market_data: dict, output_path: str = "report.html"):
        template_str = """
        <html>
        <head><style>body{font-family:sans-serif;} .alert{color:red;} .header{background:#222; color:#fff; padding:10px;}</style></head>
        <body>
            <div class="header">
                <h1>Turtle Terminal - Daily Brief</h1>
                <h3>{{ date }}</h3>
            </div>

            <h2>Market Pulse</h2>
            <p>FII Net: <strong>{{ fii_net }}</strong> | Retail Sentiment: <strong>{{ retail_sent }}</strong></p>

            <h2>Alerts</h2>
            <ul>
            {% for alert in alerts %}
                <li class="alert">{{ alert }}</li>
            {% endfor %}
            </ul>

            <h2>Cross-Market Accumulation</h2>
            <p>Stocks showing Price + OI + Delivery spikes:</p>
            <ul>
            {% for stock in accumulation_stocks %}
                <li>{{ stock }}</li>
            {% endfor %}
            </ul>

            <hr>
            <small>Generated by Jules. Cross-check all signals.</small>
        </body>
        </html>
        """

        t = Template(template_str)
        html = t.render(
            date=date.today(),
            fii_net=market_data.get('fii_net', 'N/A'),
            retail_sent=market_data.get('retail_sent', 'N/A'),
            alerts=market_data.get('alerts', []),
            accumulation_stocks=market_data.get('accumulation', [])
        )

        with open(output_path, "w") as f:
            f.write(html)

        print(f"Report generated at {output_path}")
        # pdfkit.from_file(output_path, output_path.replace('.html', '.pdf')) # Requires binary
