from sqlalchemy.orm import Session
import os
import sys

# Setup path and database connection
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from backend.infrastructure.db import SessionLocal
from backend.ingest.nse_models import CorporateAction

db: Session = SessionLocal()

try:
    print("Finding synthesized corporate actions...")

    # Find all synthesized records (those ending with ')' and starting with 'Dividend' and missing ex_date, or containing 'Record date not yet declared')
    # Because there might be some false positives, let's look for exact patterns generated by the old code
    records = db.query(CorporateAction).filter(
        CorporateAction.purpose.like("Dividend - Record date not yet declared%") |
        CorporateAction.purpose.like("Dividend (%)")
    ).all()

    count = len(records)
    print(f"Found {count} synthesized corporate actions to delete.")

    for r in records:
        db.delete(r)

    db.commit()
    print("Cleanup complete.")

except Exception as e:
    db.rollback()
    print(f"Error: {e}")
finally:
    db.close()
